apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "NSKKLIo+6pvcCNRPUUoXccOcHnw3ybBh6i/C3TWlUxttr765/jQiGXJJIa/1Rl1+\nrcy9WeKMwv2nVTlXE2+LaNMICaIu12k+sDakSxyiUP9nkqXFXphmhaMeVGjOFR1e\nZe9eyHmechf2UU5GTv4RwXNxgrrc65k4/ZOYwAGHAuQ="
